version: '2.2'

services:
    pwn:
        build: ./
        volumes: 
            - ./app:/app
        ports:
            - "24311:24311"
        expose:
            - "80"
        entrypoint:
            - "bash"
            - "-c"
            - "cd /app && python2 /app/main.py"

        pids_limit: 1024
        cpus: 0.5
        restart: unless-stopped
        
networks:
    default:
        external:
            name: pwn